### ISSUE TITLE
Register broke the matching feature

### ISSUE THREAD

**Issue by Vincentvanleeuwen** [Vincentvanleeuwen/DatingApp#10]
Because we have changed the register/login option it has caused the match function to fail.

**Comment by roelandvs** [comment]
Ik heb even gekeken, en wat mij opvalt is dat `unratedDogs` nergens binnen deze post request een waarde meekrijgt. Daar kan je nog even naar kijken.

https://github.com/Vincentvanleeuwen/DatingApp/blob/f91ca94fab431da5d59c551c6a6cfcc1eff14213/routes/match.js#L153
