### ISSUE TITLE
Register | Add images & password

### ISSUE THREAD

**Issue by Vincentvanleeuwen** [Vincentvanleeuwen/DatingApp#21]
At the moment we can't upload images in the form.
We need to apply multer to the form.

The dogModel needs to be updated so we can send the password to the database.

**Comment by roelandvs** [comment]
Ik ga hier nu aan werken, maar ik ga het password voor nu als een string opslaan in de database. Als we tijd overhebben zal ik gaan kijken naar het password hashen.

**Comment by Vincentvanleeuwen** [comment]
Dat password hashen kun je voor nu even laten zitten! Als het goed is heeft lauryn hier al onderzoek voor gedaan, en gaat zij dit implementeren.
